solver:
  sdf_scale: 0.9
  resolution: 160
  save_sdf: False

model:
  name: graph_vqvae_v1

  channel: 4
  depth: 6
  nout: 4
  depth_out: 6
  full_depth: 4
  bottleneck: 4
  resblock_type: basic
  code_channel: 16
  resblk_num: 4

  embed_dim: 3
  n_embed: 8192

data:
  train:
    name: shapenet

    # octree building
    depth: 6
    offset: 0.0
    full_depth: 4
    node_dis: True
    split_label: True

    # no data augmentation
    disable: False
    distort: False

    # data loading
    location: /data/checkpoints/xiongbj/DualOctreeGNN-Pytorch-HR/data/ShapeNet/dataset_256
    filelist: /data/checkpoints/xiongbj/DualOctreeGNN-Pytorch-HR/data/ShapeNet/filelist/train_airplane.txt
    load_sdf: False
    load_occu: False
    batch_size: 8
    shuffle: True
    # num_workers: 0

    point_scale: 0.5
    point_sample_num: 10000
    sample_surf_points: False
    in_memory: False
    num_workers: 8


  test:
    name: shapenet

    # octree building
    depth: 6
    offset: 0.0
    full_depth: 4
    node_dis: True
    split_label: True

    # no data augmentation
    disable: False
    distort: False

    # data loading
    location: /data/checkpoints/xiongbj/DualOctreeGNN-Pytorch-HR/data/ShapeNet/dataset_256
    filelist: /data/checkpoints/xiongbj/DualOctreeGNN-Pytorch-HR/data/ShapeNet/filelist/test_airplane.txt
    batch_size: 8
    load_sdf: False
    load_occu: False
    shuffle: False
    # num_workers: 0

    point_scale: 0.5
    point_sample_num: 10000
    sample_surf_points: False
    in_memory: False
    num_workers: 8
